---
ceph_user: "ceph"
controller: "control"
compute: "compute01"
openstack_glance_pool: "images"
openstack_cinder_pool: "volumes"
openstack_nova_pool: "vms"
openstack_cinder_backup_pool: "backup"
ceph_conf: "/etc/ceph/ceph.conf"
ceph_path: "/etc/ceph/"
ceph_home: "/home/ceph/"
ceph_image: "/etc/ceph/ceph.client.images.keyring"
ceph_volumes: "/etc/ceph/ceph.client.volumes.keyring"
ceph_nova: "/etc/ceph/ceph.client.nova.keyring"
ceph_backup: "/etc/ceph/ceph.client.backup.keyring"
image_key: "AQASdqVYbLsmAxAAryi71GUYt2V6JZbiRIQCmQ=="
volumes_key: "AQASdqVYHNaNHxAAxtTUgjmAV701vZkEhy8e5Q=="
nova_key: "AQA0XKVYyiIYHxAAkXPXPtwqRi7WnnaFcuJvYg=="
backup_key: "AQATdqVYeTHOBBAA9kdUFcsM3PNs/Fr4RMfVRw=="
glance_conf: "/etc/glance/glance-api.conf"
cinder_uuid: "8182df0e-183f-4f4c-8059-3e34f72ad566"
backup_uuid: "d0f25dfe-858d-47af-8e6d-e715ce50b9d9"
nova_uuid: "3670598c-59b5-4597-8e6b-ae88354bdd34"
cinder_xml: "cinder.xml"
backup_xml: "backup.xml"
nova_xml: "nova.xml"
cinder_conf: "/etc/cinder/cinder.conf"
nova_conf: "/etc/nova/nova.conf"